//! Generates this plugin's permission set from its command list.

/// Every command the plugin exposes. `tauri-plugin` turns each into
/// `allow-<command>` / `deny-<command>` permissions under `permissions/autogenerated/`.
const COMMANDS: &[&str] = &[
    "connect",
    "disconnect",
    "list_sessions",
    "session_summary",
    "transports",
    "search",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
