#!/usr/bin/env python3
"""Draw design/icon.svg to Apple's icon grid, then render the master PNG.

The grid figures here were measured off this machine rather than looked up:
`NSWorkspace.icon(forFile:)` renders what macOS actually composites for a
system app, and every one of them lands on the same shape.
"""

import math
import pathlib
import subprocess
import sys

CANVAS = 1024
BODY = 824          # 100px of margin on every side
INSET = (CANVAS - BODY) / 2
R = 270.0           # corner span, measured
N = 2.65            # superellipse exponent, measured
SEGMENTS = 96       # per corner


def corner(cx, cy, sx, sy):
    """Sample one superellipse quadrant, centre (cx, cy), heading (sx, sy)."""
    pts = []
    for i in range(SEGMENTS + 1):
        t = (math.pi / 2) * i / SEGMENTS
        x = cx + sx * R * (math.cos(t) ** (2.0 / N))
        y = cy + sy * R * (math.sin(t) ** (2.0 / N))
        pts.append((x, y))
    return pts


def body_path():
    """|x/r|^n + |y/r|^n = 1 at each corner, straight edges between.

    A plain `rx` rounded rect is a circular arc, which reads as a visibly
    different shape at this radius. Rendered against a real system mask the
    superellipse disagrees on 244 pixels of a 3000px perimeter; the best
    circle manages 4.2px RMS where this holds 1.0px.
    """
    lo, hi = INSET, INSET + BODY
    quads = [
        (hi - R, lo + R, 1, -1),   # top-right
        (hi - R, hi - R, 1, 1),    # bottom-right
        (lo + R, hi - R, -1, 1),   # bottom-left
        (lo + R, lo + R, -1, -1),  # top-left
    ]
    pts = []
    for cx, cy, sx, sy in quads:
        arc = corner(cx, cy, sx, sy)
        # Each quadrant is sampled from its horizontal axis round to its
        # vertical one, so half of them run against the outline and have to
        # be walked backwards to keep the path from crossing itself.
        pts.extend(list(reversed(arc)) if (sx * sy) < 0 else arc)
    d = [f"M {pts[0][0]:.3f} {pts[0][1]:.3f}"]
    d += [f"L {x:.3f} {y:.3f}" for x, y in pts[1:]]
    d.append("Z")
    return " ".join(d)


SVG = """<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">
  <!--
    Generated by dev/icon/build.py. Edit that, not this.

    The body is 824x824 inside 1024x1024, with a superellipse corner spanning
    270px at an exponent of 2.65. Every icon macOS ships is drawn to exactly
    that shape, so anything else reads as the wrong size or the wrong corner
    next to them in the Dock.

    Nothing here bakes in a shadow, a bevel or a top-edge highlight. macOS
    supplies those itself now, and art that carries its own gets them twice.
  -->
  <defs>
    <linearGradient id="tile" x1="0.1" y1="0" x2="0.6" y2="1">
      <stop offset="0%"   stop-color="#232830"/>
      <stop offset="52%"  stop-color="#13171c"/>
      <stop offset="100%" stop-color="#090a0c"/>
    </linearGradient>
    <linearGradient id="wire" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%"   stop-color="#7db8ff"/>
      <stop offset="100%" stop-color="#2f7fe0"/>
    </linearGradient>
    <clipPath id="body">
      <path d="__BODY__"/>
    </clipPath>
  </defs>

  <path d="__BODY__" fill="url(#tile)"/>

  <g clip-path="url(#body)">
    <g transform="translate(512 512) scale(__MARK__) translate(-512 -512)">
      <!-- a route across the network: reads as a Z, and as a traced path -->
      <g fill="none" stroke="url(#wire)" stroke-width="52"
         stroke-linecap="round" stroke-linejoin="round">
        <path d="M 318 350 L 706 350 L 318 674 L 706 674"/>
      </g>
      <!-- the nodes the route passes through -->
      <g fill="#0a0b0d" stroke="#9ecbff" stroke-width="26">
        <circle cx="318" cy="350" r="42"/>
        <circle cx="706" cy="674" r="42"/>
      </g>
    </g>
  </g>
</svg>
"""

root = pathlib.Path(__file__).resolve().parents[2]
svg = root / "design" / "icon.svg"
png = root / "design" / "icon.png"

# The mark was drawn against a body of 896; hold its proportion on the real one.
svg.write_text(SVG.replace("__BODY__", body_path()).replace("__MARK__", f"{BODY / 896:.5f}"))

# Supersample: a dark gradient across 824px steps through too few 8-bit values
# to stay smooth, and downsampling from 4096 dithers it below banding.
subprocess.run(["rsvg-convert", "-w", "4096", "-h", "4096", "-o", str(png), str(svg)], check=True)
try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required to downsample the master PNG")
Image.open(png).convert("RGBA").resize((1024, 1024), Image.LANCZOS).save(png)
print(f"wrote {svg.relative_to(root)} and {png.relative_to(root)} (1024x1024)")
